version: "3.5"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [ db ]        
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: pw
      POSTGRES_USER: postgres
      POSTGRES_DB: testDb 
    ports:
      - "5432:5432"
